name: Build Sonic Mania Plus APK with SuperCancel

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout RSDKv5-Decompilation
      uses: actions/checkout@v4
      with:
        repository: Rubberduckycooly/RSDKv5-Decompilation
        submodules: recursive

    - name: Clone SuperCancel Mod
      run: |
        cd android/app/jni
        git clone https://github.com/MegAmi24/Mania-Decomp-Mods.git
        cd Mania-Decomp-Mods/SuperCancel
        git clone https://github.com/RSDKModding/RSDKv5-GameAPI.git --recursive
        mv RSDKv5-GameAPI GameAPI

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2

    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      with:
        ndk-version: '25.2.9519653'

    - name: Build APK
      run: |
        cd android
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Sonic-Mania-Plus-SuperCancel-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
